### PR TITLE
feat: added attachment parameter to slack sendMessage def

### PR DESCRIPTION
**Pull request by ilkerispir**

### CODE REVIEW

**Comment by ilkerispir** [comment]
Hello @alfespa17, @jcanizalez,

I added attachment parameter to Slack notification function. Because, we want to similar experience like Terraform Cloud. Cloud you please review my PR when you're available?

**Comment by alfespa17** [comment]
Thank you @ilkerispir

**Comment by adamlc** [comment]
It looks like the examples may need updating after this update because they no longer work.

@ilkerispir would you mind sharing your config for the attachments? I'm looking for something similar. Thanks!

**Comment by alfespa17** [comment]
Hello @adamlc I have update the slack extension adding a method ***"sendMessageWithoutAttachment"***, I will update the documentation.

@ilkerispir when you have some free time could you send an small example of the attachment feature to this README.md

https://github.com/AzBuilder/terrakube-extensions/blob/main/groovy/SlackApp/README.md

**Comment by ilkerispir** [comment]
Hello @alfespa17, @alfespa17;

Sure, of course. I will update the README.md file when I am available.

**Comment by adamlc** [comment]
Thank you both!

**Comment by ilkerispir** [comment]
Hello @alfespa17, 

I created a PR about your request. Could you please review my PR when you're available?

FYI: @adamlc

PR: https://github.com/AzBuilder/terrakube-extensions/pull/35

**Comment by alfespa17** [comment]
I have merge the change @ilkerispir, I think you can test it now @adamlc

**Comment by adamlc** [comment]
Great thanks for the example!

With the following code:

```yaml
- runtime: "GROOVY"
  priority: 100
  after: true
  script: |
    @Grapes([
      @Grab('com.slack.api:slack-api-client:1.21.2')
    ])
    import SlackApp
    import com.slack.api.model.Attachment;

    Attachment attachment = Attachment.builder()
      .title("Run Planned - Needs Confirmation")
      .footer(String.format('%tF', java.time.LocalDateTime.now()))
      .color("#FFAC1C")
      .build();

    new SlackApp().sendMessage(
        "#infrastructure-notifications", 
        "Run notification for <https://ui.terrakube.appital.io/workspaces/$workspaceId|$SLACK_NAME>", 
        "$SLACK_TOKEN", 
        Arrays.asList(attachment),
        terrakubeOutput);
```

I can produce the following, which is probably enough for me right now!
image

**Pull request merged**
