### PR TITLE
feat: adding microsoft teams extension

### LINKED ISSUE #13: Add Microsoft Teams support
Send notification to teams.

Reference:
https://docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications

### PR DESCRIPTION
**Pull request by igorbrites**
This PR adds an extension to send messages from Terrakube to Microsoft teams using the Incoming Webhook connector.

image

### CODE REVIEW

**Comment by alfespa17** [comment]
This is great @igorbrites, maybe you can add a little image to pull request to see how it looks when you have it ready

**Comment by igorbrites** [comment]
I'm facing this error, though idk what it means

```
Begin Execution: 
Cannot invoke "String.length()" because "<parameter2>" is null
End Execution... 
```

<details><summary>Here's the full log</summary>

```
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.executor.ExecutorJobImpl - Create Job for Organization <REDACTED> Workspace <REDACTED> 
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - User Home Directory: /home/cnb
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Workspace git clone directory: /home/cnb/.terraform-spring-boot/executor/<REDACTED>/<REDACTED>
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - vcsType: PUBLIC
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.SetupWorkspaceImpl - https://github.com/<REDACTED>: Authentication is required but no CredentialsProvider has been registered
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.security.WorkspaceSecurityImpl - Generate Dex Authentication Private Token
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Executor WorkingDir: /home/cnb/.terraform-spring-boot/executor/<REDACTED>/<REDACTED>
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.executor.ExecutorJobImpl - /home/cnb/.terraform-spring-boot/executor/<REDACTED>/<REDACTED>/commitHash.info (No such file or directory)
[threadPoolTaskExecutor-1] INFO org.terrakube.client.dex.DexCredentialAuthentication - Authentication error 401
[threadPoolTaskExecutor-1] ERROR org.terrakube.client.dex.DexCredentialAuthentication - Generate Dex Authentication Private Token
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.executor.ExecutorJobImpl - Execute Groovy Script for Organization <REDACTED> Workspace <REDACTED> 
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - ScriptPath: file:/home/cnb/.terraform-spring-boot/executor/<REDACTED>/<REDACTED>/userScript.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Found 10 groovy files
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: Context.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: Infracost.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: MessageCard.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: MicrosoftTeams.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: Opa.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: Sendgrid.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: SlackApp.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: Snyk.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: TerraTag.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Loading Groovy: Terrascan.groovy
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.scripts.groovy.GroovyEngine - Execute Groovy scriptContent: 
 import MicrosoftTeams
import MessageCard

MessageCard message = new MessageCard('0078D7', 'Hello from Terrakube!', 'Hello Terrakube!')

message
  .setActivity('My activity title', 'Activity subtitle')
  .setButtons([
    'Go to Terrakube site!': 'https://www.terrakube.org',
    'Terrakube docs': 'https://docs.terrakube.org'
  ])
  .setFacts([
    'Fact 1': 'Value 1',
    'Fact 2': 'Value 2'
  ])

new MicrosoftTeams().sendMessage(message);
// "Teams Message Completed..."

[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.scripts.groovy.GroovyEngine - Cannot invoke "String.length()" because "<parameter2>" is null
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.plugin.tfoutput.aws.AwsTerraformOutputImpl - blobKey: tfoutput/<REDACTED>/11/c73edf48-f288-40f5-ba08-58ccb8c76a62.tfoutput
[threadPoolTaskExecutor-1] WARN com.amazonaws.util.Base64 - JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.status.UpdateJobStatusImpl - Job 11 is still active
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.status.UpdateJobStatusImpl - JobStatus: failed
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.status.UpdateJobStatusImpl - StepId: c73edf48-f288-40f5-ba08-58ccb8c76a62
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.status.UpdateJobStatusImpl - output: 1167
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.status.UpdateJobStatusImpl - outputError: 0
```
</details>

**Comment by alfespa17** [comment]
I am not sure but maybe you can change this part

// "Teams Message Completed..."

to 

"Teams Message Completed..."

If I remember correctly groovy extension must return a "string" like that at the end

**Comment by igorbrites** [comment]
I had tried that before and it didn't work either:

```
***************************************
Command Priority 100
Running GROOVY
Script Information:  
import MicrosoftTeams
import MessageCard

MessageCard message = new MessageCard('0078D7', 'Hello from Terrakube!', 'Hello Terrakube!')

message
  .setActivity('My activity title', 'Activity subtitle')
  .setButtons([
    'Go to Terrakube site!': 'https://www.terrakube.org',
    'Terrakube docs': 'https://docs.terrakube.org'
  ])
  .setFacts([
    'Fact 1': 'Value 1',
    'Fact 2': 'Value 2'
  ])

new MicrosoftTeams().sendMessage(message);
"Teams Message Completed..."




***************************************
Begin Execution: 
Cannot invoke "String.length()" because "<parameter2>" is null
End Execution... 
```

**Comment by alfespa17** [comment]
Quick comment to read an environment variable inside your script you can use the following example 

```groovy
new SlackApp().sendMessageWithoutAttachment(
              "#general", 
              "Hello Terrakube!", 
              "$SLACK_TOKEN", 
              terrakubeOutput);
```

And $SLACK_TOKEN is an environment variable define at workspace level instead of reading it like this: 

`System.getenv('MSTEAMS_WEBHOOK_URL')`

So in your case you could use it like this:
```
new MicrosoftTeams("$MSTEAMS_WEBHOOK_URL").sendMessage(message);
```

**Comment by igorbrites** [comment]
> Hello @igorbrites
> 
> Quick comment to read an environment variable inside your script you can use the following example
> 
> ```groovy
> new SlackApp().sendMessageWithoutAttachment(
>               "#general", 
>               "Hello Terrakube!", 
>               "$SLACK_TOKEN", 
>               terrakubeOutput);
> ```
> 
> And $SLACK_TOKEN is an environment variable define at workspace level instead of reading it like this:
> 
> `System.getenv('MSTEAMS_WEBHOOK_URL')`
> 
> So in your case you could use it like this:
> 
> ```
> new MicrosoftTeams("$MSTEAMS_WEBHOOK_URL").sendMessage(message);
> ```

That was exactly the issue I was facing, when I tried to get the environment variable it was `null` all the time, thanks for sharing!

Now I'm getting 400s from Teams, trying to understand why—but progressing nonetheless!

**Comment by igorbrites** [comment]
Working! Using the following template:

```yaml
flow:
- type: "customScripts"
  step: 100
  commands:
  - runtime: "GROOVY"
    priority: 100
    after: true
    script: |
      import MicrosoftTeams
      import MessageCard

      MessageCard message = new MessageCard('0078D7', 'Hello from Terrakube!', 'Hello Terrakube!')

      message
        .setActivity('My activity title', 'Activity subtitle')
        .setButtons([
          'Go to Terrakube site!': 'https://www.terrakube.org',
          'Terrakube docs': 'https://docs.terrakube.org'
        ])
        .setFacts([
          'Fact 1': 'Value 1',
          'Fact 2': 'Value 2'
        ])

      new MicrosoftTeams("$MSTEAMS_WEBHOOK_URL").sendMessage(message);
      "Teams Message Completed..."
```

The message is shown like this:

image

**Comment by alfespa17** [comment]
This is great @igorbrites, nice job!!! 

quick question where do you get the web hook url? I would like to test it?

**Comment by igorbrites** [comment]
> This is great @igorbrites, nice job!!!
> 
> quick question where do you get the web hook url? I would like to test it?

Thanks!

To create a webhook:

- Go to Teams, click on the Teams button on the left:
  image

- Create a channel if you don't have one already;
- Click on the three dots on your channel, and then "Manage channel":
  image

- On the settings tab, under "Connectors", click "Edit":
  image

- Search for the "Incoming webhook" connector, then click "Configure"
  image

- Fill in the connector name and optionally upload an icon for your connector, then click "Create":
  image

- It will show you the webhook URL, then you can click the button to copy it:
  image

- Then create the env var like you said before;
- Profit!

**Comment by igorbrites** [comment]
@alfespa17 I've opened the PR for your review, so take a look whenever you can 😄

**Comment by alfespa17** [comment]
> @alfespa17 I've opened the PR for your review, so take a look whenever you can 😄

I will check it today 👍 once I finish a few things from work

**Comment by alfespa17** [comment]
Thank you for your contribution @igorbrites

**Comment by alfespa17** [comment]
By the way if you would like to add something about ms teams integration using this extension to https://docs.terrakube.io I could create the page.

**Comment by igorbrites** [comment]
> By the way if you would like to add something about ms teams integration using this extension to https://docs.terrakube.io I could create the page.

Absolutely! Will create a PR there and send it your way.

**Pull request merged**
